### ISSUE TITLE
Error forking fleet

### ISSUE THREAD

**Issue by vididuc** [NebraLtd/helium-controllino#4]
Hello all

I tried to fork the fleet but get this error

Error!Error: can not read an implicit mapping pair; a colon is missed (110:7) 107 | miner-log: 108 | watchdog-log: 109 | pktfwdr: 110 | dbus -------------^

Any hint on that?

Regards,
Marcos

**Comment by shawaj** [comment]
Can you give me access to the device on Balena?

gh_shawaj is my username

Then I can take a look directly

**Comment by vididuc** [comment]
how can I do that?
Actually my device is in the fleet HELIUM-CONTROLLINO as I did not manage to get the fleet forked...

**Comment by shawaj** [comment]
You can't if it's in the open fleet.

Is there a particular reason you want to fork it?

As this will mean you won't get automatic updates

**Comment by vididuc** [comment]
Yes my device is in the open fleet.
As far as I understood if I fork it I will have the balena dashboard for free. I just wanted to get a look at the dashboard to decide what is more important for me aztomatic updates or the free balena dashboard.

**Comment by shawaj** [comment]
You can do that if you want with the forking. But then we can't see the devices on our side. So we can only help if you add one of us to be able to see the device on Balena

**Comment by vididuc** [comment]
ok I understood.
I retired just before writing this message and know what? Now it worked but I do not know why...
I guess we can close the issue.

**Comment by shawaj** [comment]
Ok let's close this for now 😊

And if you have another issue going forward, please just create a new issue here.

It could have just been something like a incorrectly copied device variable or something
