### ISSUE TITLE
Error: no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by pixelcatcher** [NebraLtd/helium-controllino#5]
[Info]              Starting build for helium-controllino2, user gh_pixelcatcher
[Info]              Dashboard link: https://dashboard.balena-cloud.com/apps/2013860/devices
[Info]              Building on arm01
[Info]              No suitable previous release for caching, skipping cache pull
[Info]              Uploading images
[Success]           Successfully uploaded images
[Error]             Some services failed to build:
[Error]               Service: diagnostics
[Error]                 Error: no matching manifest for linux/arm64/v8 in the manifest list entries
[Info]              Built on arm01
[Error]             Not deploying release.

**Comment by shawaj** [comment]
How are you pushing to the fleet?

**Comment by shawaj** [comment]
Reopening as pyhelper is failing currently

**Comment by shawaj** [comment]
Closed by https://github.com/NebraLtd/helium-miner-software/pull/616

**Comment by shawaj** [comment]
Seems to be working https://github.com/NebraLtd/helium-rak/issues/19#issuecomment-1418259072

**Comment by shawaj** [comment]
If you are finding our open source software useful than please consider sponsoring our efforts at https://github.com/sponsors/NebraLtd

And please share to others as well 🙂

We have lots of cool features coming up!
