### ISSUE TITLE
Onboarding possible ?.

### ISSUE THREAD

**Issue by Nitro62210** [NebraLtd/helium-controllino#7]
hello , im french and i have a Controllino V1 but the Onboarding is Dead...
many help from controlinno but nothing... (Mac adress on hellium app is already Nothing...)
so with Neebra Support im go to flash my SD to Firmware Version	2023.02.07.0-28 (79364b4)

But the Dashboard is ok with my RPI but no action for onboarding ? or just me dont See it ?

thx for your support

**Comment by shawaj** [comment]
if you have a not-onboarded controllino, we can help you to onboard it, but we would need to create a new key for the ECC chip and add it to our Nebra onboarding server so you can onboard it.

It will cost $75

You can create a support ticket at https://support.nebra.com to request this

**Comment by shawaj** [comment]
CC @WayneNebra

**Comment by WayneNebra** [comment]
Please create a ticket and ask for my self, @fouad-semaan or @salmanfarisvp and we can sort this out for you. 

Welcome to Nebra. 🙂

@shawaj

**Comment by shawaj** [comment]
@Nitro62210 see above
